[package]
name = "bruma"
version = "1.4.0"
description = "Editor Markdown de escritorio: ligero, local y simple."
authors = ["mindbreaker81"]
edition = "2021"
license = "MIT"

[lib]
name = "bruma_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64 = "0.22"
rfd = "0.15.4"
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
tauri-plugin-store = "2"

[lints]
rust = { warnings = "warn" }
